"use client";
import {FormEvent,useEffect,useState} from "react";
import {Crown,Music2,Newspaper,Sparkles,Users,ArrowLeft} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
type Row=Record<string,unknown>;
export default function AdminDashboard(){const[allowed,setAllowed]=useState<boolean|null>(null),[status,setStatus]=useState("");useEffect(()=>{fetch('/api/auth/me').then(async r=>{if(!r.ok)return setAllowed(false);setAllowed(Boolean((await r.json()).profile?.isAdmin))})},[]);async function action(payload:Row){const r=await fetch('/api/hub',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();setStatus(r.ok?'Saved — the class site is updated.':d.error||'Could not save.');return r.ok}if(allowed===null)return <main className="admin-page"><p>Checking admin access…</p></main>;if(!allowed)return <main className="admin-page denied"><Crown/><h1>Admin only</h1><p>This dashboard is only available to the class administrator.</p><a href="/"><ArrowLeft/> Back home</a></main>;return <main className="admin-page"><header><a href="/"><ArrowLeft/> Home</a><div><Crown/><b>THE QUEENS</b><span>CLASS OF 28</span></div></header><section className="admin-hero"><Crown/><h1>ADMIN DASHBOARD</h1><p>Everything you publish here appears for the class straight away.</p></section>{status&&<p className="admin-status">{status}</p>}<SongAdmin action={action}/><NewsAdmin action={action}/><BestiesAdmin action={action}/></main>}
function SongAdmin({action}:{action:(p:Row)=>Promise<boolean>}){const[title,setTitle]=useState(''),[artist,setArtist]=useState('');return <AdminCard icon={<Music2/>} title="Song of the Day"><form onSubmit={async e=>{e.preventDefault();if(await action({action:'set_song',title,artist})){setTitle('');setArtist('')}}}><label>SONG NAME<Input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>ARTIST<Input value={artist} onChange={e=>setArtist(e.target.value)} required/></label><Button>PUBLISH SONG</Button></form></AdminCard>}
function NewsAdmin({action}:{action:(p:Row)=>Promise<boolean>}){const[category,setCategory]=useState('drama'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);let imageKey='';if(file){const f=new FormData();f.append('file',file);const r=await fetch('/api/upload',{method:'POST',body:f}),d=await r.json();if(!r.ok){setBusy(false);return}imageKey=d.key}if(await action({action:'publish_news',category,title,body,imageKey})){setTitle('');setBody('');setFile(null)}setBusy(false)}return <AdminCard icon={category==='drama'?<Sparkles/>:<Newspaper/>} title="Newsletter Editor"><form onSubmit={submit}><label>SECTION<select value={category} onChange={e=>setCategory(e.target.value)}><option value="drama">Weekly Drama</option><option value="school">Weekly Newsletter</option><option value="besties">Best Friends Feature</option></select></label><label>HEADLINE<Input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>COVER IMAGE<Input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>STORY<Textarea rows={8} value={body} onChange={e=>setBody(e.target.value)} required/></label><Button disabled={busy}>{busy?'PUBLISHING…':'PUBLISH EDITION'}</Button></form></AdminCard>}
function BestiesAdmin({action}:{action:(p:Row)=>Promise<boolean>}){const[names,setNames]=useState(['','','']);return <AdminCard icon={<Users/>} title="Best Friends Voting"><form onSubmit={async e=>{e.preventDefault();if(await action({action:'set_besties',names}))setNames(['','',''])}}>{names.map((n,i)=><label key={i}>CANDIDATE {i+1}<Input value={n} onChange={e=>setNames(x=>x.map((v,j)=>j===i?e.target.value:v))} placeholder="One name or a pair" required/></label>)}<Button>SAVE CANDIDATES</Button></form></AdminCard>}
function AdminCard({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="admin-card"><h2>{icon}{title}</h2>{children}</section>}
