"use client";
import {FormEvent,useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {ArrowLeft,Crown,Newspaper,Sparkles} from "lucide-react";

type Row=Record<string,unknown>;type Hub={profile?:{is_admin?:number};news?:Row[];candidates?:Row[];myBestieVote?:Row|null};
const imageSrc=(v:unknown)=>{const s=String(v||"");return !s?"":s.startsWith("http")||s.startsWith("/")?s:`/api/media/${s}`};
export default function NewsletterPage({category}:{category:string}){
 const[hub,setHub]=useState<Hub>({}),[selected,setSelected]=useState<number>(),[status,setStatus]=useState("");
 const load=()=>fetch("/api/hub",{cache:"no-store"}).then(r=>r.json()).then(setHub);useEffect(()=>{load()},[]);
 const post=async(payload:Row)=>{const r=await fetch("/api/hub",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setStatus(d.error||"Could not save.");return false}await load();return true};
 const items=hub.news?.filter(n=>n.category===category)||[],admin=Boolean(hub.profile?.is_admin);
 if(category==="besties"&&!items.length)return <Shell icon={<Crown/>} title="Best Friends of the Week"><p className="newspaper-deck">Choose one pair, then press Submit Vote. The winning friendship feature will appear here after the result is announced.</p><div className="besties in-newsletter">{[0,1,2].map(i=>{const c=hub.candidates?.[i];return <button key={i} className={selected===Number(c?.id)?"bestie-selected":""} onClick={()=>setSelected(Number(c?.id))}><Crown/><span>0{i+1}</span><b>{String(c?.name||`Bestie 0${i+1}`)}</b><small>{String(c?.votes||0)} VOTES</small></button>})}</div><Button disabled={!selected} onClick={async()=>{if(await post({action:"vote_bestie",candidateId:selected}))setStatus("Your vote was submitted.")}}>Submit Vote</Button>{status&&<p className="vote-status">{status}</p>}{admin&&<Editor category="besties" onSaved={load}/>}</Shell>;
 const title=category==="drama"?"Weekly Drama":category==="besties"?"Best Friends Spotlight":"Weekly Newsletter";
 return <Shell icon={category==="drama"?<Sparkles/>:category==="besties"?<Crown/>:<Newspaper/>} title={title}>{items.length===0&&<p className="newspaper-deck">No issue has been published yet.</p>}{items.map((n,i)=><article className="news-detail" key={String(n.id)}><div className="issue-line"><span>{i===0?"LATEST ISSUE":"ARCHIVE"}</span><time>{new Date(Number(n.created_at)).toLocaleDateString()}</time></div><h2>{String(n.title)}</h2>{n.image_key&&<img src={imageSrc(n.image_key)} alt={String(n.title)}/>}<p>{String(n.body)}</p></article>)}{admin&&<Editor category={category} onSaved={load}/>}</Shell>
}
function Editor({category,onSaved}:{category:string;onSaved:()=>void}){const[title,setTitle]=useState(""),[body,setBody]=useState(""),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState("");async function submit(e:FormEvent){e.preventDefault();setBusy(true);setStatus("");try{let imageKey="";if(file){const form=new FormData();form.append("file",file);const up=await fetch("/api/upload",{method:"POST",body:form});const ud=await up.json();if(!up.ok)throw new Error(ud.error);imageKey=ud.key}const r=await fetch("/api/hub",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"publish_news",category,title,body,imageKey})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTitle("");setBody("");setFile(null);setStatus("Published.");onSaved()}catch(e){setStatus(e instanceof Error?e.message:"Could not publish.")}finally{setBusy(false)}}return <form className="admin-panel" onSubmit={submit}><p className="eyebrow">ADMIN EDITOR</p><h3>Create a new edition</h3><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Article headline" required/><Input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><Textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write the full story…" rows={10} required/><Button disabled={busy}>{busy?"Publishing…":"Publish Edition"}</Button>{status&&<p>{status}</p>}</form>}
function Shell({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <main className="newsletter-page"><header><a href="/#newsletter"><ArrowLeft/> Back to Newsletter</a><span>CLASS OF 28 · THE PINK EDITION</span></header><section><div className="page-icon">{icon}</div><div className="edition-rule"><span>SPECIAL EDITION</span><time>{new Date().toLocaleDateString()}</time></div><h1>{title}</h1>{children}</section></main>}
