"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { AvatarEditor, EmojiPicker } from "./member-extras";
import { Polls, ClassCalendar } from "./polls-calendar";
import { Ban, CalendarDays, ChevronLeft, ChevronRight, Crown, Heart, Home, Lightbulb, MessageCircle, Music2, Newspaper, Sparkles, UserRound, Vote, ShieldCheck, Trash2, Megaphone, Check, Eye } from "lucide-react";

const names = ["rose sh","samar","wed","rose dos","rana","leen","lubna","nora","taleen","ghina","haneen","aljazy","jana","lama","jumana","fatima","noran","sara","hessa","aljoharah","alkawthar","zahraa","zainab","aqilah"];
const banned = ["67","six seven","fuck","bitch","bitchy","shit","shitty","cunt","whore","ass","hoe","كلي زق","كلي زقين","كل زق","كل زقين","كلبه","ملعونه","خايسه","اكرهك","بضربك","قبيحه","قحبه","حماره","مياو","كلب","قدرات","تحصيلي","بترول","جامعه","قياس","سديد","مبكر","المبكر","النسبه","مس ساره","مس سارا","الاداره","استاذه ساره","استاذه سارا","انسه ساره","انسه سارا","دبه","نحيفه","نحيف","دب","pussy","fat","fatty","صلعه","ام اربع عيون","نيرد","nerd"];
const greetings = ["Welcome back, {name}! You look beautiful today.","Hi, {name}! The smartest girl just arrived.","Welcome, gorgeous {name}.","Look who’s here — our favorite girl, {name}.","Hello, {name}! Today looks better with you in it.","There she is — the lovely {name}.","Welcome, {name}! The main character has arrived.","Hey, {name}! You make this class brighter."];
const energy = ["You deserve a beautiful day.","Be proud of how far you’ve come.","Your energy makes every room brighter.","You are loved more than you realize.","Today is another chance to shine.","Take a breath — you’re doing just fine."];
const rules = ["This website belongs to our class only.","I will not share screenshots, messages, passwords, or private content outside the class.","I will respect everyone and will not use the website to bully, threaten, insult, or embarrass another student."];
type Profile={avatarKey?:string;id:number;realName:string;nickname:string;email:string;isAdmin?:boolean};
type Message={id:number;body:string;realName:string;nickname:string;createdAt:string;authorId?:number;avatarKey?:string;channel?:'class'|'admin';reactions?:{kind:string;count:number;mine:number}[]};
type Row=Record<string,unknown>;
type Hub={profile?:{is_admin?:number;nickname?:string};polls?:Row[];options?:Row[];myPollVotes?:Row[];events?:Row[];songs?:Row[];news?:Row[];comments?:Row[];candidates?:Row[];myBestieVote?:Row|null;settings?:Record<string,string>};
const imageSrc=(v:unknown)=>{const s=String(v||"");return !s?"":s.startsWith("http")||s.startsWith("/")?s:`/api/media/${s}`};

export default function ClassHub(){
 const[profile,setProfile]=useState<Profile|null>(null),[ready,setReady]=useState(false),[hub,setHub]=useState<Hub>({}),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[activeChat,setActiveChat]=useState<'class'|'admin'>('class'),[error,setError]=useState("");
 const greeting=useMemo(()=>greetings[Math.floor(Math.random()*greetings.length)],[]), positive=useMemo(()=>energy[Math.floor(Math.random()*energy.length)],[]);
 useEffect(()=>{fetch('/api/auth/me',{cache:'no-store'}).then(async r=>{if(r.ok)setProfile((await r.json()).profile)}).finally(()=>setReady(true))},[]);
 const load=useCallback(async()=>{if(!profile)return;const r=await fetch("/api/hub",{cache:"no-store"});const d=await r.json();if(r.ok)setHub(d)},[profile]);
 const loadMessages=useCallback(async()=>{if(!profile)return;const r=await fetch("/api/messages",{cache:"no-store"});const d=await r.json();if(r.ok)setMessages(d.messages||[])},[profile]);
 useEffect(()=>{load();loadMessages()},[load,loadMessages]);
 async function act(payload:Row){const r=await fetch("/api/hub",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setError(d.error||"Could not save.");return false}setError("");await load();return true}
 async function send(e:FormEvent){e.preventDefault();if(!profile||!draft.trim())return;const r=await fetch("/api/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:draft,channel:activeChat})});const d=await r.json();if(!r.ok)return setError(d.error||"Could not post.");setDraft("");setError("");await loadMessages()}
 async function removeMessage(id:number){const removed=messages.find(m=>m.id===id);setMessages(old=>old.filter(m=>m.id!==id));setError("");try{const r=await fetch(`/api/messages?id=${id}`,{method:"DELETE",signal:AbortSignal.timeout(15000)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Could not delete.")}catch(e){if(removed)setMessages(old=>[...old,removed].sort((a,b)=>a.id-b.id));setError(e instanceof Error?e.message:"Could not delete. Try again.")}}
 async function react(messageId:number,kind:string){const previous=messages.find(m=>m.id===messageId);setError("");setMessages(old=>old.map(m=>{if(m.id!==messageId)return m;const reactions=[...(m.reactions||[])],index=reactions.findIndex(r=>r.kind===kind);if(index<0)reactions.push({kind,count:1,mine:1});else{const old=reactions[index];reactions[index]={...old,mine:old.mine?0:1,count:old.count+(old.mine?-1:1)}}return {...m,reactions:reactions.filter(r=>r.count>0)}}));try{const r=await fetch("/api/messages",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({messageId,kind}),signal:AbortSignal.timeout(15000)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"Could not react.")}catch(e){if(previous)setMessages(old=>old.map(m=>m.id===messageId?previous:m));setError(e instanceof Error?e.message:"Could not react.")}}
 if(!ready)return null;if(!profile)return <Entry onEnter={setProfile}/>;
 const weekly=(hub.events||[]).filter(e=>{const now=new Date(),date=new Date(String(e.event_date)+"T00:00:00"),end=new Date(now);end.setDate(now.getDate()+7);return date>=new Date(now.getFullYear(),now.getMonth(),now.getDate())&&date<=end}).slice(0,5);
 const nav=[['home','Home',Home],['chat','Chat',MessageCircle],['polls','Polls',Vote],['calendar','Calendar',CalendarDays],['newsletter','Newsletter',Newspaper],['banned','Banned Words',Ban],['suggestions','Suggestions',Lightbulb],['song','Song of the Day',Music2],['profile','Profile',UserRound]] as const;
 return <main className="pink-site"><header className="pink-masthead"><div><Crown/><strong>THE QUEENS</strong><span>CLASS OF 28</span></div><nav>{profile.isAdmin&&<a href="/admin"><ShieldCheck/> ADMIN</a>}<button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setProfile(null);setHub({})}}>SIGN OUT</button></nav></header><div className="blog-layout"><aside className="side-nav"><p>NAVIGATION</p>{nav.map(([id,label,Icon])=><a key={id} href={`#${id}`}><Icon/>{label}</a>)}</aside><div className="blog-main">
 <section id="home" className="top-area"><article className="welcome-card"><span>WELCOME!</span><h1>{greeting.replace("{name}",profile.nickname)}</h1><p>Our little Class of 28 corner — made for memories, laughter, and everything worth remembering.</p></article><article className="energy-card"><Sparkles/><span>POSITIVE ENERGY</span><h2>{positive}</h2><div className="doodle-row"><Heart/><Sparkles/><Crown/></div></article><article className="week-strip"><div><CalendarDays/><b>Important Events This Week</b></div><div className="week-events">{weekly.length?weekly.map(e=><button key={String(e.id)} onClick={()=>document.querySelector('#calendar')?.scrollIntoView({behavior:'smooth'})}><time>{String(e.event_date)}</time><strong>{String(e.title)}</strong></button>):<p>No important events this week — enjoy the calm.</p>}</div><a href="#calendar">View full calendar</a></article></section>
 <Section id="chat" eyebrow="TWO ROOMS, ONE CLASS" title="Class Chats"><div className="chat-tabs"><button className={activeChat==='class'?'active':''} onClick={()=>setActiveChat('class')}><MessageCircle/> Class Chat <small>Everyone can post</small></button><button className={activeChat==='admin'?'active':''} onClick={()=>setActiveChat('admin')}><Megaphone/> Admin Updates <small>Announcements only</small></button></div><div className="chat-room-note">{activeChat==='class'?'Talk, react, and keep it kind.':'Official class updates from the admin.'}</div><div className="chat-window">{messages.filter(m=>(m.channel||'class')===activeChat).length?messages.filter(m=>(m.channel||'class')===activeChat).map(m=><article className="message" key={m.id}><div className="avatar">{m.avatarKey?<img src={imageSrc(m.avatarKey)} alt=""/>:m.nickname[0]?.toUpperCase()}</div><div className="message-body"><div className="message-head"><span><b>{m.nickname}</b><small>{m.realName}</small></span>{(profile.isAdmin||m.authorId===profile.id)&&<button className="delete-message" onClick={()=>removeMessage(m.id)} aria-label="Delete message"><Trash2/></button>}</div><p>{m.body}</p><div className="message-reactions">{m.reactions?.map(r=><button key={r.kind} className={r.mine?'mine':''} onClick={()=>react(m.id,r.kind)}><span>{({love:'❤️',agree:'✅',seen:'👀'} as Record<string,string>)[r.kind]||r.kind}</span> {r.count}</button>)}<EmojiPicker onPick={emoji=>react(m.id,emoji)}/></div></div></article>):<p className="empty-note">{activeChat==='class'?'No messages yet. Be the first to say something.':'No admin updates yet.'}</p>}</div>{(activeChat==='class'||profile.isAdmin)&&<form className="composer" onSubmit={send}><Input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={activeChat==='admin'?'Write an admin update…':`Message as ${profile.nickname}…`}/><Button>{activeChat==='admin'?'Publish Update':'Post'}</Button></form>}{activeChat==='admin'&&!profile.isAdmin&&<p className="admin-readonly"><ShieldCheck/> Only the admin can publish here.</p>}</Section>
 <Section id="polls" eyebrow="ASK THE CLASS" title="Polls"><Polls hub={hub} act={act}/></Section>
 <Section id="calendar" eyebrow="PLAN IT PRETTY" title="Class Calendar"><p>Every member can add an event. Choose a date or press Add Event.</p><ClassCalendar hub={hub} act={act}/></Section>
 <Section id="newsletter" eyebrow="THE CLASS EDITION" title="Newsletter"><NewsletterCards hub={hub}/><BestieVote hub={hub} act={act}/></Section>
 <Section id="banned" eyebrow="KEEP IT CUTE, KEEP IT KIND" title="Banned Words"><div className="banned-cute"><div className="banned-title"><Ban/><div><h2>NOT IN OUR CHAT</h2><p>These words and topics stay outside our Class of 28 space.</p></div><Sparkles/></div><div className="banned-stickers">{banned.map((w,i)=><span key={w} className={`sticker s${i%6}`} style={{transform:`rotate(${[-4,3,-2,5,1,-3][i%6]}deg)`,fontSize:`${[.88,1.08,1.28,.96,1.15,.82][i%6]}rem`}}>{i%7===0?'! ':''}{w}</span>)}</div><p className="banned-footer"><Heart/> Words matter. Make the chat feel safe for everyone. <Heart/></p></div></Section>
 <Section id="suggestions" eyebrow="DEAR THE QUEENS" title="Suggestions"><SuggestionBox/></Section>
 <Section id="song" eyebrow="NOW PLAYING" title="Song of the Day"><SongPanel hub={hub} act={act}/></Section>
 <Section id="profile" eyebrow="MEMBER FILE" title={profile.nickname}><div className="profile-card"><UserRound/><div><b>{profile.nickname}</b><p>{profile.realName} · {profile.email}</p></div></div><AvatarEditor avatarKey={profile.avatarKey} onSaved={key=>{setProfile(old=>old?{...old,avatarKey:key}:old);loadMessages()}}/><ChangePassword/></Section>
 {error&&<p className="floating-error">{error}</p>}</div></div><footer>XOXO · CLASS OF 28</footer></main>
}

function Section({id,eyebrow,title,children}:{id:string;eyebrow:string;title:string;children:React.ReactNode}){return <section id={id} className="paper-section"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>}
function Entry({onEnter}:{onEnter:(p:Profile)=>void}){const[mode,setMode]=useState<'login'|'register'>('login'),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[realName,setRealName]=useState(""),[nickname,setNickname]=useState(""),[checks,setChecks]=useState([false,false,false]),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password,realName,nickname,agreed:checks.every(Boolean)})});const d=await r.json();if(!r.ok){setError(d.error||'Could not continue.');setBusy(false);return}const me=await fetch('/api/auth/me',{cache:'no-store'}),m=await me.json();onEnter(m.profile);setBusy(false)}return <main className="entry pink-entry"><section><Crown/><p>CLASS OF 28</p><h1>the queens</h1><h2>{mode==='login'?'Welcome Back':'Create Your Account'}</h2><div className="auth-tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>SIGN IN</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>NEW ACCOUNT</button></div><form className="auth-form" onSubmit={submit}><Input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address"/><Input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (8+ characters)"/>{mode==='register'&&<><select value={realName} onChange={e=>setRealName(e.target.value)}><option value="">Choose your real name</option>{names.map(n=><option key={n}>{n}</option>)}</select><Input value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Choose your nickname"/>{rules.map((r,i)=><Label key={r} className="covenant"><Checkbox checked={checks[i]} onCheckedChange={v=>setChecks(x=>x.map((a,j)=>j===i?Boolean(v):a))}/><span>{r}</span></Label>)}</>}<Button disabled={busy||!email||password.length<8||(mode==='register'&&(!realName||nickname.trim().length<2||checks.some(x=>!x)))}>{busy?'PLEASE WAIT…':mode==='login'?'SIGN IN':'CREATE ACCOUNT'}</Button>{error&&<p className="auth-error">{error}</p>}</form></section></main>}
function NewsletterCards({hub}:{hub:Hub}){const cards=[{category:'besties',title:'Best Friends Spotlight',kicker:'FRIENDSHIP EDITION',icon:Crown},{category:'drama',title:'Weekly Drama',kicker:'EXCLUSIVE',icon:Sparkles},{category:'school',title:'Weekly Newsletter',kicker:'THE WEEK AHEAD',icon:Newspaper}];return <div className="newsstand">{cards.map(({category,title,kicker,icon:Icon})=>{const n=hub.news?.find(x=>x.category===category);return <a href={`/newsletter/${category}`} key={category}><div className="paper-top"><span>CLASS OF 28</span><time>{new Date().toLocaleDateString()}</time></div><Icon/><small>{kicker}</small><h3>{String(n?.title||title)}</h3><div className="fake-photo">{n?.image_key?<img src={imageSrc(n.image_key)} alt=""/>:<span>GG</span>}</div><p>{String(n?.body||'Open this edition to read the full story.')}</p><b>READ FULL STORY</b></a>})}</div>}
function BestieVote({hub,act}:{hub:Hub;act:(p:Row)=>Promise<boolean>}){const[selected,setSelected]=useState<number|undefined>(hub.myBestieVote?.candidate_id as number|undefined),[status,setStatus]=useState("");return <div className="bestie-vote"><p className="eyebrow">SUNDAY — TUESDAY</p><h3>Vote for Best Friends of the Week</h3><div>{[0,1,2].map(i=>{const c=hub.candidates?.[i];return <button key={i} className={selected===Number(c?.id)?'selected':''} onClick={()=>setSelected(Number(c?.id))}><Heart/><b>{String(c?.name||`Besties 0${i+1}`)}</b><small>{String(c?.votes||0)} votes</small></button>})}</div><Button disabled={!selected} onClick={async()=>{if(await act({action:'vote_bestie',candidateId:selected}))setStatus('Your vote was submitted.')}}>Submit Vote</Button>{status&&<p>{status}</p>}</div>}
function SuggestionBox(){const[v,setV]=useState(""),[status,setStatus]=useState("");return <form className="cute-form" onSubmit={async e=>{e.preventDefault();const r=await fetch('/api/suggestions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:v})});if(r.ok){setV('');setStatus('Sent. The Queens is listening.')}}}><Textarea value={v} onChange={e=>setV(e.target.value)} placeholder="I think we should…"/><Button>Send suggestion</Button>{status&&<p>{status}</p>}</form>}
function ChangePassword(){const[currentPassword,setCurrent]=useState(""),[newPassword,setNext]=useState(""),[confirm,setConfirm]=useState(""),[status,setStatus]=useState("");return <form className="cute-form password-form" onSubmit={async e=>{e.preventDefault();if(newPassword!==confirm)return setStatus('New passwords do not match.');const r=await fetch('/api/auth/change-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();setStatus(r.ok?'Password changed. Your login is still saved.':d.error||'Could not change password.');if(r.ok){setCurrent('');setNext('');setConfirm('')}}}><h3>Change Password</h3><Input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} placeholder="Current password"/><Input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNext(e.target.value)} placeholder="New password (8+ characters)"/><Input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm new password"/><Button disabled={!currentPassword||newPassword.length<8||!confirm}>Update Password</Button>{status&&<p>{status}</p>}</form>}
function SongPanel({hub,act}:{hub:Hub;act:(p:Row)=>Promise<boolean>}){const[t,setT]=useState(""),[a,setA]=useState("");const admin=Boolean(hub.profile?.is_admin);return <div className="song-layout"><div className="song-cover"><MailIcon/><div><small>SONG OF THE DAY</small><h3>{hub.settings?.song_title||'Glamorous'}</h3><p>{hub.settings?.song_artist||'Fergie'}</p></div></div><form className="cute-form" onSubmit={async e=>{e.preventDefault();if(await act({action:admin?'set_song':'suggest_song',title:t,artist:a})){setT('');setA('')}}}><Input value={t} onChange={e=>setT(e.target.value)} placeholder="Song title"/><Input value={a} onChange={e=>setA(e.target.value)} placeholder="Artist"/><Button>{admin?'Set Song':'Suggest Song'}</Button></form></div>}
function MailIcon(){return <div className="mail-icon"><Heart/></div>}
